### ISSUE TITLE
Build failing on Cloudflare 

### ISSUE THREAD

**Issue by aagavin** [aagavin/randyhub#4]
<pre class="c_ev c_aq c_au c_av c_lb c_lc c_bi c_fp c_lu c_ls c_lt c_fb c_fc c_cd c_ld">

15:05:52.332	Initializing build environment. This may take up to a few minutes to complete
15:06:56.791	Success: Finished initializing build environment
15:06:56.791	Cloning repository...
15:06:58.586	Success: Finished cloning repository files
15:06:58.819	Installing dependencies
15:06:58.838	Python version set to 2.7
15:07:01.842	v12.18.0 is already installed.
15:07:02.205	Now using node v12.18.0 (npm v6.14.4)
15:07:02.226	Started restoring cached build plugins
15:07:02.236	Finished restoring cached build plugins
15:07:02.568	Attempting ruby version 2.7.1, read from environment
15:07:03.772	Using ruby version 2.7.1
15:07:04.071	Using PHP version 5.6
15:07:04.100	5.2 is already installed.
15:07:04.103	Using Swift version 5.2
15:07:04.103	Started restoring cached node modules
15:07:04.105	Finished restoring cached node modules
15:07:04.231	Installing NPM modules using NPM version 6.14.4
15:07:34.534	
15:07:34.534	> core-js@2.6.12 postinstall /opt/buildhome/repo/node_modules/babel-runtime/node_modules/core-js
15:07:34.534	> node -e "try{require('./postinstall')}catch(e){}"
15:07:34.534	
15:07:34.577	[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
15:07:34.578	
15:07:34.578	[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
15:07:34.578	[96m>[94m https://opencollective.com/core-js [0m
15:07:34.578	[96m>[94m https://www.patreon.com/zloirock [0m
15:07:34.578	
15:07:34.578	[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
15:07:34.578	
15:07:34.609	
15:07:34.609	> core-js@3.18.2 postinstall /opt/buildhome/repo/node_modules/core-js
15:07:34.609	> node -e "try{require('./postinstall')}catch(e){}"
15:07:34.609	
15:07:34.645	[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
15:07:34.645	
15:07:34.646	[96mThe project needs your help! Please consider supporting of core-js:[0m
15:07:34.646	[96m>[94m https://opencollective.com/core-js [0m
15:07:34.646	[96m>[94m https://patreon.com/zloirock [0m
15:07:34.646	[96m>[94m https://paypal.me/zloirock [0m
15:07:34.646	[96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
15:07:34.646	
15:07:34.646	[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
15:07:34.646	
15:07:34.652	
15:07:34.652	> core-js-pure@3.18.2 postinstall /opt/buildhome/repo/node_modules/core-js-pure
15:07:34.652	> node -e "try{require('./postinstall')}catch(e){}"
15:07:34.652	
15:07:34.710	
15:07:34.711	> ejs@2.7.4 postinstall /opt/buildhome/repo/node_modules/ejs
15:07:34.711	> node ./postinstall.js
15:07:34.711	
15:07:34.744	Thank you for installing [35mEJS[0m: built with the [32mJake[0m JavaScript build tool ([32mhttps://jakejs.com/[0m)
15:07:34.744	
15:07:36.606	npm WARN The package eslint is included as both a dev and production dependency.
15:07:36.606	npm WARN The package stylelint is included as both a dev and production dependency.
15:07:36.606	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
15:07:36.607	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
15:07:36.607	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
15:07:36.607	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
15:07:36.607	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
15:07:36.608	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
15:07:36.608	
15:07:36.615	added 2153 packages from 836 contributors and audited 2161 packages in 30.442s
15:07:37.631	
15:07:37.631	194 packages are looking for funding
15:07:37.631	  run `npm fund` for details
15:07:37.631	
15:07:37.631	found 24 vulnerabilities (8 moderate, 15 high, 1 critical)
15:07:37.631	  run `npm audit fix` to fix them, or `npm audit` for details
15:07:37.901	NPM modules installed
15:07:38.107	Installing Hugo 0.54.0
15:07:38.936	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
15:07:38.937	Started restoring cached go cache
15:07:38.939	Finished restoring cached go cache
15:07:39.335	go version go1.14.4 linux/amd64
15:07:39.338	go version go1.14.4 linux/amd64
15:07:39.348	Installing missing commands
15:07:39.348	Verify run directory
15:07:39.348	Executing user command: npm run build
15:07:39.563	
15:07:39.563	> randyhub@0.1.0 build /opt/buildhome/repo
15:07:39.563	> react-scripts build
15:07:39.563	
15:07:40.898	Creating an optimized production build...
15:07:49.371	Failed to compile.
15:07:49.372	
15:07:49.372	src/routes/CovidCounter/index.js
15:07:49.372	  Line 30:16:  Unexpected console statement                no-console
15:07:49.372	  Line 33:41:  Each then() should return a value or throw  promise/always-return
15:07:49.372	  Line 47:17:  Unexpected negated condition                no-negated-condition
15:07:49.372	  Line 58:19:  Missing "key" prop for element in iterator  react/jsx-key
15:07:49.373	
15:07:49.373	src/routes/GitRepo/index.js
15:07:49.373	  Line 32:52:  Each then() should return a value or throw  promise/always-return
15:07:49.373	  Line 75:24:  Missing "key" prop for element in iterator  react/jsx-key
15:07:49.373	  Line 96:24:  Missing "key" prop for element in iterator  react/jsx-key
15:07:49.373	
15:07:49.373	Search for the keywords to learn more about each error.
15:07:49.373	
15:07:49.373	
15:07:49.388	npm ERR! code ELIFECYCLE
15:07:49.389	npm ERR! errno 1
15:07:49.389	npm ERR! randyhub@0.1.0 build: `react-scripts build`
15:07:49.389	npm ERR! Exit status 1
15:07:49.389	npm ERR! 
15:07:49.389	npm ERR! Failed at the randyhub@0.1.0 build script.
15:07:49.389	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
15:07:49.449	
15:07:49.449	npm ERR! A complete log of this run can be found in:
15:07:49.449	npm ERR!     /opt/buildhome/.npm/_logs/2021-10-07T19_07_49_390Z-debug.log
15:07:49.453	Failed: build command exited with code: 1
</pre>

**Comment by aagavin** [comment]
```
15:05:52.332	Initializing build environment. This may take up to a few minutes to complete
15:06:56.791	Success: Finished initializing build environment
15:06:56.791	Cloning repository...
15:06:58.586	Success: Finished cloning repository files
15:06:58.819	Installing dependencies
15:06:58.838	Python version set to 2.7
15:07:01.842	v12.18.0 is already installed.
15:07:02.205	Now using node v12.18.0 (npm v6.14.4)
15:07:02.226	Started restoring cached build plugins
15:07:02.236	Finished restoring cached build plugins
15:07:02.568	Attempting ruby version 2.7.1, read from environment
15:07:03.772	Using ruby version 2.7.1
15:07:04.071	Using PHP version 5.6
15:07:04.100	5.2 is already installed.
15:07:04.103	Using Swift version 5.2
15:07:04.103	Started restoring cached node modules
15:07:04.105	Finished restoring cached node modules
15:07:04.231	Installing NPM modules using NPM version 6.14.4
15:07:34.534	
15:07:34.534	> core-js@2.6.12 postinstall /opt/buildhome/repo/node_modules/babel-runtime/node_modules/core-js
15:07:34.534	> node -e "try{require('./postinstall')}catch(e){}"
15:07:34.534	
15:07:34.577	[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
15:07:34.578	
15:07:34.578	[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
15:07:34.578	[96m>[94m https://opencollective.com/core-js [0m
15:07:34.578	[96m>[94m https://www.patreon.com/zloirock [0m
15:07:34.578	
15:07:34.578	[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
15:07:34.578	
15:07:34.609	
15:07:34.609	> core-js@3.18.2 postinstall /opt/buildhome/repo/node_modules/core-js
15:07:34.609	> node -e "try{require('./postinstall')}catch(e){}"
15:07:34.609	
15:07:34.645	[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
15:07:34.645	
15:07:34.646	[96mThe project needs your help! Please consider supporting of core-js:[0m
15:07:34.646	[96m>[94m https://opencollective.com/core-js [0m
15:07:34.646	[96m>[94m https://patreon.com/zloirock [0m
15:07:34.646	[96m>[94m https://paypal.me/zloirock [0m
15:07:34.646	[96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
15:07:34.646	
15:07:34.646	[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
15:07:34.646	
15:07:34.652	
15:07:34.652	> core-js-pure@3.18.2 postinstall /opt/buildhome/repo/node_modules/core-js-pure
15:07:34.652	> node -e "try{require('./postinstall')}catch(e){}"
15:07:34.652	
15:07:34.710	
15:07:34.711	> ejs@2.7.4 postinstall /opt/buildhome/repo/node_modules/ejs
15:07:34.711	> node ./postinstall.js
15:07:34.711	
15:07:34.744	Thank you for installing [35mEJS[0m: built with the [32mJake[0m JavaScript build tool ([32mhttps://jakejs.com/[0m)
15:07:34.744	
15:07:36.606	npm WARN The package eslint is included as both a dev and production dependency.
15:07:36.606	npm WARN The package stylelint is included as both a dev and production dependency.
15:07:36.606	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
15:07:36.607	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
15:07:36.607	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
15:07:36.607	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
15:07:36.607	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
15:07:36.608	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
15:07:36.608	
15:07:36.615	added 2153 packages from 836 contributors and audited 2161 packages in 30.442s
15:07:37.631	
15:07:37.631	194 packages are looking for funding
15:07:37.631	  run `npm fund` for details
15:07:37.631	
15:07:37.631	found 24 vulnerabilities (8 moderate, 15 high, 1 critical)
15:07:37.631	  run `npm audit fix` to fix them, or `npm audit` for details
15:07:37.901	NPM modules installed
15:07:38.107	Installing Hugo 0.54.0
15:07:38.936	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
15:07:38.937	Started restoring cached go cache
15:07:38.939	Finished restoring cached go cache
15:07:39.335	go version go1.14.4 linux/amd64
15:07:39.338	go version go1.14.4 linux/amd64
15:07:39.348	Installing missing commands
15:07:39.348	Verify run directory
15:07:39.348	Executing user command: npm run build
15:07:39.563	
15:07:39.563	> randyhub@0.1.0 build /opt/buildhome/repo
15:07:39.563	> react-scripts build
15:07:39.563	
15:07:40.898	Creating an optimized production build...
15:07:49.371	Failed to compile.
15:07:49.372	
15:07:49.372	src/routes/CovidCounter/index.js
15:07:49.372	  Line 30:16:  Unexpected console statement                no-console
15:07:49.372	  Line 33:41:  Each then() should return a value or throw  promise/always-return
15:07:49.372	  Line 47:17:  Unexpected negated condition                no-negated-condition
15:07:49.372	  Line 58:19:  Missing "key" prop for element in iterator  react/jsx-key
15:07:49.373	
15:07:49.373	src/routes/GitRepo/index.js
15:07:49.373	  Line 32:52:  Each then() should return a value or throw  promise/always-return
15:07:49.373	  Line 75:24:  Missing "key" prop for element in iterator  react/jsx-key
15:07:49.373	  Line 96:24:  Missing "key" prop for element in iterator  react/jsx-key
15:07:49.373	
15:07:49.373	Search for the keywords to learn more about each error.
15:07:49.373	
15:07:49.373	
15:07:49.388	npm ERR! code ELIFECYCLE
15:07:49.389	npm ERR! errno 1
15:07:49.389	npm ERR! randyhub@0.1.0 build: `react-scripts build`
15:07:49.389	npm ERR! Exit status 1
15:07:49.389	npm ERR! 
15:07:49.389	npm ERR! Failed at the randyhub@0.1.0 build script.
15:07:49.389	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
15:07:49.449	
15:07:49.449	npm ERR! A complete log of this run can be found in:
15:07:49.449	npm ERR!     /opt/buildhome/.npm/_logs/2021-10-07T19_07_49_390Z-debug.log
15:07:49.453	Failed: build command exited with code: 1
```

**Comment by anson-li** [comment]
Fixing!
