### ISSUE TITLE
Builds failing

### ISSUE THREAD

**Issue by aagavin** [aagavin/randyhub#45]
Builds failing 

see https://github.com/aagavin/randyhub/pulls

**Comment by ColinT** [comment]
Need logs or log access to triage this ticket.

**Comment by aagavin** [comment]
@ColinT we use cloudflair to build and deploy. I can add you and @anson-li.


For now here is an example logs
[randyhub.a3f64240-b917-4d9a-8cdc-f9e26a58eaec.log](https://github.com/aagavin/randyhub/files/8655500/randyhub.a3f64240-b917-4d9a-8cdc-f9e26a58eaec.log)

**Comment by ColinT** [comment]
The error is:
```
Failed to load plugin 'import' declared in '.eslintrc.js » eslint-config-airbnb » /opt/buildhome/repo/node_modules/eslint-config-airbnb-base/index.js » /opt/buildhome/repo/node_modules/eslint-config-airbnb-base/rules/imports.js': Package subpath './lib/util/glob-util' is not defined by "exports" in /opt/buildhome/repo/node_modules/eslint/package.json
```

Seems like this could be a version incompatibility between `eslint-plugin-import` and `eslint@^8` introduced by #46 . Updating dependencies and subdependencies to `eslint-plugin-import@latest`, or downgrading to `eslint@^7` may resolve.

**Comment by aagavin** [comment]
Cool, thanks @ColinT. Will look into it soon.
